# Get the list of doctors
GET http://localhost:3000/patients HTTP/1.1

###
GET http://localhost:3000/patients/1 HTTP/1.1

###
GET http://localhost:3000/patients/niss/640511-123-45 HTTP/1.1

###
GET http://localhost:3000/patients/1/short HTTP/1.1

###
GET http://localhost:3000/patients/zipcode/1000 HTTP/1.1

###
GET http://localhost:3000/patients/doctor/1/zipcode/1000 HTTP/1.1